### PR TITLE
merge staging to main

### PR DESCRIPTION
**Pull request by katherinemwong**

### CODE REVIEW

**Review by bennett-zhang — CHANGES_REQUESTED** [review]
Sorry, there is a bug with this pull request. Add an audio object, then add another one with the same name. A popup will appear saying you can't add an audio object with the same name. Close a popup. Add a new audio object, this time with a valid name. Refresh, and the audio card will disappear. If it didn't disappear, click on the audio card, and the page will be blank.

**Comment by katherinemwong** [comment]
@SailorForSchool add the bug fixes when u can

**Review by Emmanuel-Serrano — APPROVED** [review]
All test pass except one because our playwright dependency, which for now is fine, along with the codacy not passing because of some variables that were 
technique not used but it is fine for now since we got to get our changes onto main. Bug described by benett has also been fix.

**Review by SailorForSchool — APPROVED** [review]
I approve - please remove codacy check the code looks fine to me

**Pull request merged**
